baseURL = "https://krystianbucko.com/"
languageCode = "en-us"
title = "Krystian's Blog"
theme = "hugo-atlantic-theme"
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 3

[params]
  google_analytics_id = "UA-172946404-1"

  [params.homepage]
    postLimit = 5
    
  [params.logo]
    showLogoTextOnDesktop = true
    showLogoTextOnMobile = true
    showLogoImageOnDesktop = true
    showLogoImageOnMobile = true
    logoDesktopText = "Krystian's Blog"
    logoDesktopImage = "images/logo/logo.png"
    logoMobileText = "Krys' Blog "
    logoMobileImage = "images/logo/logo-mobile.png"
    logoDesktopImageHeight = 32
    logoDesktopImageWidth = 32
    logoMobileImageHeight = 32
    logoMobileImageWidth = 32

  [params.fonts]
    google_fonts = "https://fonts.googleapis.com/css2?family=Fira+Mono&family=Lato:wght@300;400;700&family=Source+Sans+Pro&display=swap"
    heading = "Lato"
    base = "Source Sans Pro"
    monospace = "Fira Mono"

  [params.seo]
    meta_twitter_site = "@KrystianBucko"
    meta_twitter_creator = "@KrystianBucko"

[build]
  writeStats = true

[permalinks]
    posts = "blog/:year/:month/:title/"
    pages = ":slug/"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"
  
# Main Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3