
name: Deploy Hugo Site to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy_site:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v3'

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Upload contents to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: public
          destination: krystianbucko.com
          parent: false
