name: Push Contents To Google Cloud Storage

on:
  push:

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{secrets.WORKLOADIDENTITYFED}}'
        service_account: '${{secrets.SERVICE_ACCOUNT}}'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'public'
        destination: 'krystianbucko.com'
        parent: false